#replicaCount: 2
#image:
#repository: httpd
#tag: latest
#service:
#type: ClusterIP
#port: 80

replicaCount: 2

image:
  repository: httpd
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

resources: {}